# Generated by Django 6.0.2 on 2026-04-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
