# Generated by Django 6.0.2 on 2026-04-27 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_acta', models.CharField(choices=[('ENTREGA', 'Acta de Entrega'), ('DEVOLUCION', 'Acta de Devolución')], default='ENTREGA', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('firmada', models.BooleanField(default=False, help_text='Si está firmada, no se puede modificar')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Acta escaneada y firmada', null=True, upload_to='actas/firmadas/')),
                ('metodo_sanitizacion', models.CharField(choices=[('CLEARED', 'NIST Clear (Borrado Lógico)'), ('PURGED', 'NIST Purge (Borrado Criptográfico Irreversible)'), ('DESTROYED', 'NIST Destroy (Destrucción Física)'), ('N/A', 'No Aplica / Entrega')], default='N/A', help_text='Estándar NIST SP 800-88 aplicado al equipo', max_length=20)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
            },
        ),
    ]
