# Generated by Django 6.0.2 on 2026-04-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='ministro_de_fe',
            field=models.ForeignKey(blank=True, help_text='Administrador de obra que actúa como ministro de fe en terreno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_validadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
