# Generated by Django 6.0.2 on 2026-04-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'permissions': [('aprobar_anulacion', 'Puede aprobar anulación de actas firmadas')], 'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
        migrations.AddField(
            model_name='acta',
            name='anulada',
            field=models.BooleanField(default=False, help_text='Si está anulada, el acta queda inhabilitada'),
        ),
        migrations.AddField(
            model_name='acta',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='firmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_firmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
