# Generated by Django 6.0.2 on 2026-04-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaaccesorio',
            name='accesorio',
        ),
        migrations.RemoveField(
            model_name='entregaaccesorio',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='entregaaccesorio',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='historialasignacion',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='historialasignacion',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='historialasignacion',
            name='dispositivo',
        ),
        migrations.DeleteModel(
            name='Accesorio',
        ),
        migrations.DeleteModel(
            name='EntregaAccesorio',
        ),
        migrations.DeleteModel(
            name='HistorialAsignacion',
        ),
    ]
