# Generated by Django 6.0.2 on 2026-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_alter_acta_options_acta_anulada_acta_anulada_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
    ]
