# Generated by Django 6.0.2 on 2026-04-14 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_remove_entregaaccesorio_accesorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='metodo_sanitizacion',
            field=models.CharField(choices=[('CLEARED', 'NIST Clear (Borrado Lógico)'), ('PURGED', 'NIST Purge (Borrado Criptográfico Irreversible)'), ('DESTROYED', 'NIST Destroy (Destrucción Física)'), ('N/A', 'No Aplica / Entrega')], default='N/A', help_text='Estándar NIST SP 800-88 aplicado al equipo', max_length=20),
        ),
        migrations.AddField(
            model_name='acta',
            name='ministro_de_fe',
            field=models.ForeignKey(blank=True, help_text='Administrador de obra que actúa como ministro de fe en terreno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_validadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
