# Generated by Django 6.0.2 on 2026-05-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_alter_acta_options'),
        ('suministros', '0004_remove_marca_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='tipo_acta',
            field=models.CharField(choices=[('ENTREGA', 'Acta de Entrega'), ('DEVOLUCION', 'Acta de Devolución'), ('ENTREGA_SUMINISTROS', 'Acta de Entrega de Suministros')], default='ENTREGA', max_length=25),
        ),
        migrations.CreateModel(
            name='MovimientoStockActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='actas.acta')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='suministros.movimientostock')),
            ],
            options={
                'db_table': 'actas_movimiento_stock_acta',
                'unique_together': {('acta', 'movimiento')},
            },
        ),
    ]
