# Generated by Django 6.0.2 on 2026-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodispositivo',
            name='sigla',
            field=models.CharField(blank=True, help_text='Ej: NTBK, SMPH', max_length=10, null=True, unique=True),
        ),
    ]
