# Generated by Django 6.0.2 on 2026-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_grupos_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodispositivo',
            name='umbral_disponibilidad',
            field=models.PositiveIntegerField(default=3, help_text='Stock mínimo de equipos disponibles para semáforo verde en el Dashboard'),
        ),
    ]
