# Generated by Django 6.0.2 on 2026-04-27 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría de suministros')),
            ],
            options={
                'verbose_name': 'Categoría de Suministro',
                'verbose_name_plural': 'Categorías de Suministros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(blank=True, help_text='SKU o código de barras', max_length=50, null=True, unique=True)),
                ('marca', models.CharField(blank=True, help_text='Marca del insumo (Ej: Dataline para alternativos, o Brother si es original)', max_length=100)),
                ('es_alternativo', models.BooleanField(default=False, help_text='Marcar si es un insumo alternativo/genérico')),
                ('unidad_medida', models.CharField(default='Unidades', help_text='Ej: Unidades, Cajas, Litros', max_length=50)),
                ('stock_minimo', models.PositiveIntegerField(default=2, help_text='Nivel de alerta para reposición')),
                ('stock_actual', models.IntegerField(default=0, editable=False, help_text='Stock calculado en base a movimientos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='suministros.categoriasuministro')),
                ('modelos_compatibles', models.ManyToManyField(blank=True, help_text='Modelos de impresoras o dispositivos compatibles', related_name='suministros_compatibles', to='core.modelo')),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra)'), ('SALIDA', 'Salida (Entrega/Asignación)'), ('AJUSTE_POS', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo (Merma/Pérdida)')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del movimiento (siempre positiva)')),
                ('costo_unitario', models.PositiveIntegerField(blank=True, help_text='Costo unitario en la factura (solo entradas)', null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Razón de la merma, detalle de la entrega, etc.')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministros_cargados', to='core.centrocosto')),
                ('colaborador_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministros_recibidos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock_registrados', to=settings.AUTH_USER_MODEL)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='suministros.suministro')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
