# Generated by Django 6.0.2 on 2026-04-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dispositivos', '0002_alter_historialasignacion_dispositivo'),
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='dispositivo_destino',
            field=models.ForeignKey(blank=True, help_text='Dispositivo al que se destinó el insumo (ej: impresora)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='dispositivos.dispositivo'),
        ),
        migrations.AddField(
            model_name='suministro',
            name='fabricante',
            field=models.ForeignKey(blank=True, help_text='Fabricante del insumo (Ej: Brother, HP, Dataline)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministros', to='core.fabricante'),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='marca',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Usar fabricante en su lugar', max_length=100),
        ),
    ]
