# Generated by Django 6.0.2 on 2026-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriasuministro',
            name='tipos_dispositivo_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Tipos de dispositivos que usan esta categoría de suministros', to='core.tipodispositivo'),
        ),
    ]
