# Generated by Django 6.0.2 on 2026-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0002_categoriasuministro_tipos_dispositivo_compatibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el suministro está activo en el catálogo'),
        ),
    ]
