# Generated by Django 6.0.2 on 2026-04-30 17:04

from django.db import migrations


def migrate_marca_to_fabricante(apps, schema_editor):
    """
    Migra los datos del campo marca (VARCHAR) al nuevo campo fabricante (FK).
    Para cada Suministro con marca no vacía:
      - Si existe un Fabricante con el mismo nombre (case-insensitive), lo usa.
      - Si no, crea un Fabricante nuevo con ese nombre.
    """
    Suministro = apps.get_model('suministros', 'Suministro')
    Fabricante = apps.get_model('core', 'Fabricante')

    # Cache de fabricantes existentes (normalizados a minúsculas)
    fabricantes_cache = {}
    for fab in Fabricante.objects.all():
        fabricantes_cache[fab.nombre.lower()] = fab

    updated = 0
    created = 0

    for suministro in Suministro.objects.exclude(marca='').exclude(marca__isnull=True):
        marca_lower = suministro.marca.strip().lower()
        if not marca_lower:
            continue

        if marca_lower in fabricantes_cache:
            suministro.fabricante = fabricantes_cache[marca_lower]
            updated += 1
        else:
            # Crear el fabricante nuevo
            fab = Fabricante.objects.create(nombre=suministro.marca.strip())
            fabricantes_cache[marca_lower] = fab
            suministro.fabricante = fab
            created += 1

        suministro.save(update_fields=['fabricante'])

    print(f"  [OK] {updated} suministros vinculados a fabricantes existentes")
    print(f"  [OK] {created} nuevos fabricantes creados")


def reverse_migrate_marca_to_fabricante(apps, schema_editor):
    """
    Revierte la migración: vuelca el nombre del fabricante al campo marca.
    No borra fabricantes creados (por si están en uso en otras apps).
    """
    Suministro = apps.get_model('suministros', 'Suministro')

    for suministro in Suministro.objects.exclude(fabricante__isnull=True):
        suministro.marca = suministro.fabricante.nombre
        suministro.save(update_fields=['marca'])


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0002_add_fabricante_and_dispositivo_destino'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_marca_to_fabricante, reverse_migrate_marca_to_fabricante),
    ]
