# Generated by Django 6.0.2 on 2026-04-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0003_migrate_marca_to_fabricante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='marca',
        ),
    ]
