# Generated by Django 6.0.2 on 2026-05-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0004_remove_marca_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='duracion_estimada_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Días estimados que debería durar este insumo. Usado para alertas de consumo inusual.', null=True),
        ),
    ]
