"""
Django settings for inventario_jmie project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv  # <-- 1. Importa load_dotenv

# 2. Carga el archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Confianza en headers de proxy (Nginx en Docker)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ─────────────────────────────────────────────────────
# Validación fail-fast de variables críticas de seguridad
# ─────────────────────────────────────────────────────

# SECRET_KEY
if not SECRET_KEY or not str(SECRET_KEY).strip():
    raise ImproperlyConfigured("SECRET_KEY no está definida o está vacía.")

_secret_key_lower = str(SECRET_KEY).lower()
_insecure_prefixes = ('change-me', 'your-secret-key', 'django-insecure-')
if any(_secret_key_lower.startswith(p) for p in _insecure_prefixes) or _secret_key_lower in ('change-me', 'your-secret-key'):
    raise ImproperlyConfigured("SECRET_KEY tiene un valor placeholder inseguro.")

# ALLOWED_HOSTS
if not ALLOWED_HOSTS or (len(ALLOWED_HOSTS) == 1 and not ALLOWED_HOSTS[0].strip()):
    raise ImproperlyConfigured("ALLOWED_HOSTS no puede estar vacío.")

if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS no puede contener '*' cuando DEBUG es False.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'constance',
    'constance.backends.database',  
    'django_htmx',
    'core',
    'colaboradores.apps.ColaboradoresConfig',
    'dispositivos',
    'actas',
    'dashboard',
    'imagekit',
    'django_filters',
    'django_cotton',
    'suministros',
]


CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    'CLI_PREFIX_ID': ('JMIE', 'Prefijo para los identificadores internos de equipos'),
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'inventario_jmie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'colaboradores.Colaborador'

WSGI_APPLICATION = 'inventario_jmie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_PATH = os.getenv('DB_PATH', BASE_DIR / 'db.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # fuente
STATIC_ROOT = BASE_DIR / 'staticfiles'     # destino de collectstatic

# Media files (Uploads) — filesystem por ahora, django-storages para Azure/S3 futuro
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# ─────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'inventario.log',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'dispositivos': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'actas': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'colaboradores': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'suministros': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ─────────────────────────────────────────────────────
# Playwright PDF Configuration
# ─────────────────────────────────────────────────────
# Playwright: timeout máximo para generación de PDF (ms)
PLAYWRIGHT_BROWSER_TIMEOUT = int(os.getenv('PLAYWRIGHT_BROWSER_TIMEOUT', '15000'))

# Playwright: segundos de inactividad antes de cerrar una instancia de Chromium
PLAYWRIGHT_BROWSER_TTL = int(os.getenv('PLAYWRIGHT_BROWSER_TTL', '120'))

# Playwright: máximo de instancias de Chromium concurrentes en el pool
PLAYWRIGHT_POOL_MAX_SIZE = int(os.getenv('PLAYWRIGHT_POOL_MAX_SIZE', '2'))
