# Generated by Django 6.0.2 on 2026-04-27 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_interno', models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID Interno (Auto)')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('valor_contable', models.PositiveIntegerField(default=0, help_text='Valor en pesos chilenos')),
                ('notas_condicion', models.TextField(help_text='Detallar rayas, golpes o desgaste', verbose_name='Condición Física')),
                ('foto_equipo', models.ImageField(blank=True, null=True, upload_to='dispositivos/fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadodispositivo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelo')),
                ('propietario_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='EquipoRed',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('subtipo', models.CharField(help_text='Ej: Switch 24 puertos PoE', max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_gestion', models.GenericIPAddressField(blank=True, null=True)),
            ],
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('es_multifuncional', models.BooleanField(default=False)),
                ('tipo_tinta', models.CharField(help_text='Ej: Toner TN-660', max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_asignada', models.GenericIPAddressField(blank=True, null=True)),
            ],
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('procesador', models.CharField(max_length=100)),
                ('ram_gb', models.PositiveIntegerField(verbose_name='RAM (GB)')),
                ('almacenamiento', models.CharField(help_text='Ej: 512GB SSD', max_length=100)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_asignada', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notebook',
            },
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('rack_u', models.CharField(max_length=50, verbose_name='Ubicación en Rack')),
                ('configuracion_raid', models.CharField(blank=True, max_length=100, null=True)),
                ('procesadores_fisicos', models.PositiveIntegerField(default=1)),
                ('criticidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=50)),
            ],
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('imei_1', models.CharField(max_length=15, unique=True)),
                ('imei_2', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Smartphone',
            },
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('falla_reportada', models.TextField()),
                ('reparacion_realizada', models.TextField(blank=True, null=True)),
                ('costo_reparacion', models.PositiveIntegerField(default=0)),
                ('cambio_estado_automatico', models.BooleanField(default=False)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Bitácora de Mantenimiento',
                'verbose_name_plural': 'Bitácoras de Mantenimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntregaAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios', to='actas.acta')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesorios', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('condicion_fisica', models.TextField()),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='actas.acta')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='dispositivos.dispositivo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_contable__gte', 0)), name='valor_contable_positivo'),
        ),
    ]
