# Generated by Django 6.0.2 on 2026-04-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialasignacion',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dispositivos.dispositivo'),
        ),
    ]
