# Generated by Django 6.0.2 on 2026-04-13 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_update_estado_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dispositivos.dispositivo')),
                ('pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
            bases=('dispositivos.dispositivo',),
        ),
        migrations.AlterModelOptions(
            name='bitacoramantenimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Bitácora de Mantenimiento', 'verbose_name_plural': 'Bitácoras de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='cambio_estado_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitacoramantenimiento',
            name='tecnico_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
