# Generated by Django 6.0.2 on 2026-04-13 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ajustes_catalogos'),
        ('dispositivos', '0003_monitor_alter_bitacoramantenimiento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_contable__gte', 0)), name='valor_contable_positivo'),
        ),
    ]
