# Generated by Django 6.0.2 on 2026-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_entregaaccesorio_historialasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='identificador_interno',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID Interno (Auto)'),
        ),
    ]
