# Generated by Django 6.0.2 on 2026-04-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_remove_entregaaccesorio_accesorio_and_more'),
        ('dispositivos', '0006_alter_dispositivo_identificador_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaaccesorio',
            name='acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios', to='actas.acta'),
        ),
    ]
